# Generated by Django 6.0.8 on 2026-08-25 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom du client')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='prenom du client')),
                ('adresse_mail', models.EmailField(max_length=200, verbose_name='adresse e-mail')),
                ('contact', models.CharField(blank=True, max_length=20, verbose_name='contact')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('adresse', models.CharField(blank=True, max_length=200, verbose_name='adresse')),
                ('note', models.TextField(blank=True, help_text=' allergies, maladies, etc.', verbose_name='note')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="nom de l'entreprise ")),
                ('adresse_mail', models.EmailField(max_length=200, verbose_name='adresse e-mail')),
                ('contact', models.CharField(blank=True, max_length=20, verbose_name='contact')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('adresse', models.CharField(blank=True, max_length=200, verbose_name='adresse')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('prix_de_vente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix de vente')),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(0)], verbose_name="prix d'achat")),
                ('quantite', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='quantité en stock')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='stock')),
                ('seuil_alerte', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0)], verbose_name="seuil d'alerte")),
                ('numero_de_lot', models.CharField(blank=True, max_length=100, verbose_name='numéro de lot')),
                ('date_de_peremption', models.DateField(blank=True, null=True, verbose_name='date de péremption')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='image du produit')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='Produits.categorie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='Produits.fournisseur')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date de la vente')),
                ('mode_de_paiement', models.CharField(choices=[('ESP', 'Espèce'), ('CBK', 'Carte bancaire'), ('MM', 'Mobile Money')], default='ESP', max_length=3, verbose_name='mode de paiement')),
                ('statut', models.CharField(choices=[('ENC', 'En cours'), ('TERM', 'Terminée'), ('ANU', 'Annulée')], default='ENC', max_length=4, verbose_name='statut de la vente')),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='remise ')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('client', models.ForeignKey(blank=True, help_text='vide = client de passage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='Produits.client')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité vendue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix de vente du produit')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='Produits.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_vente', to='Produits.vente')),
            ],
        ),
    ]
