# Generated by Django 6.0.8 on 2026-08-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'categorie', 'verbose_name_plural': 'categories'},
        ),
    ]
