# Generated by Django 6.0.8 on 2026-09-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0003_alter_produit_prix_achat_alter_produit_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse_mail',
            field=models.EmailField(max_length=200, verbose_name='adresse_mail'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse_mail',
            field=models.EmailField(max_length=200, verbose_name='adresse_mail'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Produits.vente'),
        ),
    ]
