# Generated by Django 6.0.8 on 2026-09-21 12:30

import django.core.validators
from django.db import migrations, models


def remplir_totaux(apps, schema_editor):
    Vente = apps.get_model('Produits', 'Vente')
    LigneVente = apps.get_model('Produits', 'LigneVente')
    for vente in Vente.objects.all():
        sous_total = sum(
            ligne.quantite * ligne.prix_unitaire
            for ligne in LigneVente.objects.filter(vente_id=vente.pk)
        )
        vente.total = max(sous_total - vente.remise, 0)
        vente.save(update_fields=['total'])


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0004_alter_client_adresse_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='total',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='total de la vente',
            ),
        ),
        migrations.RunPython(remplir_totaux, migrations.RunPython.noop),
    ]
